#!/bin/bash
set -e
set -x

buildbranch() {
        git checkout $1
        for DIR in ampache ampache-mysql; do
                cd $DIR
                docker build -t jgoerzen/$DIR:$2 .
                cd ..
        done
}

buildbranch master latest
git checkout master

